---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---


## 網站資料爬取
```{r}
library(rvest)

ptt_postsAll<-c()

for(i in 1:20){
    
    if(i==1){
        pttContent<-read_html("https://www.ptt.cc/bbs/Tech_Job/index.html")
    }
    else{
        url<-paste0("https://www.ptt.cc",NextURL)
        pttContent<-read_html(url)
    }
    
    Title<-pttContent %>% html_nodes(".title") %>% html_text()%>%iconv(from="UTF-8",to="UTF-8")
    Title<-gsub("\\n|\\t","",Title)
    Author<-pttContent %>% html_nodes(".author") %>% html_text()
    PushNum<-pttContent %>% html_nodes(".nrec") %>% html_text()
    ptt_posts<-data.frame(Title=Title,Author=Author,PushNum=PushNum)
    ptt_postsAll<-rbind(ptt_postsAll,ptt_posts)
    
    link<-pttContent %>%html_nodes(".action-bar a") %>% html_attr('href')
    NextURL<-link[4]
    
    Sys.sleep(runif(1,2,4))
}

df<-replace(ptt_postsAll, ptt_postsAll == "-", NA)
df<-na.omit(df)
```

## 爬蟲結果呈現
```{r}
knitr::kable(df)
```

## 解釋爬蟲結果 
```{r}
nrow(df)
```

總共382篇文章

```{r}
library(data.table)
df2<-data.table(head(sort(table(df$Author),decreasing = TRUE),20))
setnames(df2,"V1","Author")
setnames(df2,"N","Count")
df2
data.table(df[grepl("wer11",df$Author),])
data.table(df[grepl("magic704226",df$Author),])
```

發文數最多的作者是wer11和magic704226
上表為兩個作者的發文標題與推文數

```{r}
subset(df,PushNum=="爆")
```
被推爆的文章

```{r}
df3<-data.table(head(sort(table(substr(df$Title,start=1,stop=4)),decreasing = T),10))
setnames(df3,"V1","Title_Category")
setnames(df3,"N","Count")
df3
```
發文標題分類前十名

發文目的以"請益"為最多
